name: Ruby

on: [push, pull_request]

jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby_version: ['2.6', '2.7']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Setup & Run
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
